import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BadgeUnlockToast } from "./components/BadgeUnlockToast";
import { LiveActivityTicker } from "./components/LiveActivityTicker";
import { Plus_Jakarta_Sans, Playfair_Display } from 'next/font/google';

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  variable: '--font-jakarta'
});

const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair'
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jakarta.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <BadgeUnlockToast />
         <LiveActivityTicker />{children}</body>
      {/* <body className="bg-black text-white">
       
        {children}
      </body> */}
    </html>
  );
}
