import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const ProductSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    description: { type: String, required: true },
    price: { type: Number, required: true },
    image: { type: String, required: true },
    tag: { type: String, default: 'NEW' },
    category: { type: String, default: 'General' },
    dopamineScore: { type: Number, default: 500 },
    isDrop: { type: Boolean, default: false },
    dropEndsAt: { type: Date, default: null },
  },
  { timestamps: true }
);

const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

const sampleProducts = [
  // --- TIMEPIECES & HOROLOGY ---
  {
    title: 'Onyx Skeleton Automatic',
    description: 'Forged carbon housing with self-winding mechanical movement and sapphire crystal back.',
    price: 48500,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85',
    tag: 'ULTRA RARE',
    category: 'Timepieces',
    dopamineScore: 2800,
    isDrop: false,
  },
  {
    title: 'Monaco Rose Gold Chronograph',
    description: '18k rose gold casing with sunray dial and hand-stitched alligator leather strap.',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1200&q=85',
    tag: 'EDITORIAL',
    category: 'Timepieces',
    dopamineScore: 2100,
    isDrop: false,
  },
  {
    title: 'Celestial Tourbillon No. 04',
    description: 'Floating tourbillon cage with genuine meteorite dial fragments and titanium bezel.',
    price: 125000,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=85',
    tag: 'LIMITED DROP',
    category: 'Timepieces',
    dopamineScore: 4500,
    isDrop: true,
    dropEndsAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 Hours from now
  },

  // --- FOOTWEAR & SNEAKERS ---
  {
    title: 'Veloce Leather High-Tops',
    description: 'Italian calfskin high-tops with hand-distressed detailing and matte gold eyelets.',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=85',
    tag: 'NEW SEASON',
    category: 'Footwear',
    dopamineScore: 1200,
    isDrop: false,
  },
  {
    title: 'Monolith Chunky Derby',
    description: 'Brushed leather lace-ups set on an exaggerated lug sole with brushed silver heel accents.',
    price: 1850,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=85',
    tag: 'MUST HAVE',
    category: 'Footwear',
    dopamineScore: 1450,
    isDrop: false,
  },

  // --- APPAREL & STREETWEAR ---
  {
    title: 'Atelier Cashmere Trench',
    description: 'Double-breasted virgin wool and cashmere blend trench coat with horn buttons.',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
    tag: 'EDITORIAL',
    category: 'Apparel',
    dopamineScore: 1900,
    isDrop: false,
  },
  {
    title: 'Holographic Streetwear Bomber',
    description: 'Heavyweight Japanese selvage denim with light-reflecting iridescent satin lining.',
    price: 2100,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=85',
    tag: 'CYBER DRIP',
    category: 'Apparel',
    dopamineScore: 1650,
    isDrop: false,
  },

  // --- AUDIO & GEAR ---
  {
    title: 'Retro Y2K Clear Headphones',
    description: 'See-through acoustic housing with active noise cancellation and planar magnetic drivers.',
    price: 1280,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85',
    tag: 'Y2K FLEX',
    category: 'Gear',
    dopamineScore: 1100,
    isDrop: false,
  },
  {
    title: 'Aero GT Matte Carbon Helmet',
    description: 'Track-ready carbon fiber helmet custom fitted with electrochromic auto-tinting visor.',
    price: 6800,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85',
    tag: 'LIMITED DROP',
    category: 'Gear',
    dopamineScore: 3200,
    isDrop: true,
    dropEndsAt: new Date(Date.now() + 12 * 60 * 60 * 1000),
  },
  {
    title: 'Cyberpunk Neon Shield Goggles',
    description: '100% UV protection with custom titanium frame and auto-adjusting polar tint.',
    price: 950,
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=1200&q=85',
    tag: 'CYBERPUNK',
    dopamineScore: 980,
    category: 'Gear',
    isDrop: false,
  },
  // --- OUTERWEAR & COATS ---
  {
    title: 'Atelier Cashmere Oversized Trench',
    description: 'Double-breasted virgin wool and cashmere blend trench coat with raglan sleeves and natural horn buttons.',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
    tag: 'EDITORIAL',
    category: 'Outerwear',
    dopamineScore: 2400,
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 8,
    rating: 4.9,
    reviewsCount: 18,
    isDrop: false,
  },
  {
    title: 'Shearling-Lined Aviator Jacket',
    description: 'Hand-burnished distressed calfskin with thick cream lambskin shearling collar and heavy brass hardware.',
    price: 5800,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=85',
    tag: 'LIMITED DROP',
    category: 'Outerwear',
    dopamineScore: 3100,
    sizes: ['M', 'L', 'XL'],
    stock: 5,
    rating: 5.0,
    reviewsCount: 9,
    isDrop: true,
    dropEndsAt: new Date(Date.now() + 18 * 60 * 60 * 1000),
  },
  {
    title: 'Iridescent Sculptural Down Puffer',
    description: 'Goose-down insulated statement coat constructed from light-reflecting metallic nylon fabric.',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
    tag: 'RUNWAY',
    category: 'Outerwear',
    dopamineScore: 1850,
    sizes: ['S', 'M', 'L'],
    stock: 12,
    rating: 4.7,
    reviewsCount: 14,
    isDrop: false,
  },

  // --- TAILORING & TOPS ---
  {
    title: 'Velvet Jacquard Evening Blazer',
    description: 'Tailored slim-fit tuxedo jacket featuring structured shoulders, satin peak lapels, and ornate floral weave.',
    price: 3400,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
    tag: 'VIP EVENING',
    category: 'Tailoring',
    dopamineScore: 2200,
    sizes: ['48EU', '50EU', '52EU', '54EU'],
    stock: 6,
    rating: 4.9,
    reviewsCount: 11,
    isDrop: false,
  },
  {
    title: 'Heavyweight Silk Satin Pajama Shirt',
    description: 'Fluid Mulberry silk button-down detailed with contrast white piping and mother-of-pearl buttons.',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=1200&q=85',
    tag: 'LOUUNGE LUXE',
    category: 'Tops',
    dopamineScore: 1400,
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 20,
    rating: 4.8,
    reviewsCount: 22,
    isDrop: false,
  },
  {
    title: 'Boxy Vintage Sun-Faded Tee',
    description: '400GSM combed organic cotton with enzyme wash treatment and subtle hand-distressed collar edges.',
    price: 480,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=85',
    tag: 'ESSENTIAL',
    category: 'Tops',
    dopamineScore: 850,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 35,
    rating: 4.6,
    reviewsCount: 45,
    isDrop: false,
  },

  // --- DENIM & TROUSERS ---
  {
    title: 'Japanese Selvage Cargo Denim',
    description: '16oz raw indigo denim trousers featuring 3D utility cargo pockets and cinch-adjustable leg cuffs.',
    price: 1650,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=85',
    tag: 'STREETWEAR',
    category: 'Bottoms',
    dopamineScore: 1600,
    sizes: ['30W', '32W', '34W', '36W'],
    stock: 15,
    rating: 4.8,
    reviewsCount: 19,
    isDrop: false,
  },
  {
    title: 'Pleated Wide-Leg Wool Trousers',
    description: 'Relaxed tailored pants crafted from tropical weight Italian wool with deep double front pleats.',
    price: 1100,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=85',
    tag: 'MINIMALIST',
    category: 'Bottoms',
    dopamineScore: 1250,
    sizes: ['28W', '30W', '32W', '34W'],
    stock: 18,
    rating: 4.9,
    reviewsCount: 16,
    isDrop: false,
  },

  // --- FOOTWEAR & SNEAKERS ---
  {
    title: 'Veloce Leather High-Top Sneakers',
    description: 'Handcrafted Italian calfskin high-tops with padded ankle collars and gold foiled crest branding.',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=85',
    tag: 'NEW SEASON',
    category: 'Footwear',
    dopamineScore: 1900,
    sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44'],
    stock: 10,
    rating: 4.9,
    reviewsCount: 31,
    isDrop: false,
  },
  {
    title: 'Monolith Chunky Derby Shoes',
    description: 'Polished brushed leather lace-ups set on an exaggerated 55mm lug sole with silver heel clips.',
    price: 1850,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=85',
    tag: 'MUST HAVE',
    category: 'Footwear',
    dopamineScore: 2100,
    sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44'],
    stock: 7,
    rating: 5.0,
    reviewsCount: 24,
    isDrop: false,
  },
  {
    title: 'Aero-Runner Technical Mesh Sneaker',
    description: 'Futuristic multi-layered runner featuring TPU cage overlays, reflective laces, and air-cushioned midsole.',
    price: 980,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=85',
    tag: 'CYBER DRIP',
    category: 'Footwear',
    dopamineScore: 1350,
    sizes: ['EU 39', 'EU 40', 'EU 41', 'EU 42', 'EU 43'],
    stock: 22,
    rating: 4.7,
    reviewsCount: 38,
    isDrop: false,
  },
  {
    title: 'Chelsea Lug Boots in Espresso Suede',
    description: 'Water-resistant Italian suede boots with elastic side gussets and durable storm-welted rubber soles.',
    price: 1600,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=1200&q=85',
    tag: 'AUTUMN DROP',
    category: 'Footwear',
    dopamineScore: 1750,
    sizes: ['EU 41', 'EU 42', 'EU 43', 'EU 44'],
    stock: 9,
    rating: 4.8,
    reviewsCount: 15,
    isDrop: false,
  },
  // --- OUTERWEAR & COATS ---
  {
    title: 'Atelier Cashmere Oversized Trench',
    description: 'Double-breasted virgin wool and cashmere blend trench coat with raglan sleeves and natural horn buttons.',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
    tag: 'EDITORIAL',
    category: 'Outerwear',
    dopamineScore: 2400,
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 8,
    rating: 4.9,
    reviewsCount: 18,
    isDrop: false,
    reviews: [
      {
        author: 'Julian V.',
        rating: 5,
        comment: 'The drape on this trench is incredible. Pure cashmere warmth without feeling heavy.',
        date: '2 days ago',
        verifiedPurchase: true,
      },
      {
        author: 'Elena R.',
        rating: 5,
        comment: 'Runs slightly oversized—fits perfectly over structured blazers.',
        date: '1 week ago',
        verifiedPurchase: true,
      },
    ],
  },
  {
    title: 'Shearling-Lined Aviator Bomber',
    description: 'Hand-burnished distressed calfskin with thick cream lambskin shearling collar and heavy brass hardware.',
    price: 5800,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=85',
    tag: 'LIMITED DROP',
    category: 'Outerwear',
    dopamineScore: 3100,
    sizes: ['M', 'L', 'XL'],
    stock: 5,
    rating: 5.0,
    reviewsCount: 9,
    isDrop: true,
    dropEndsAt: new Date(Date.now() + 18 * 60 * 60 * 1000),
    reviews: [
      {
        author: 'Marcus B.',
        rating: 5,
        comment: 'The leather smell and craftsmanship are top-tier. Total showstopper.',
        date: '3 days ago',
        verifiedPurchase: true,
      },
    ],
  },
  {
    title: 'Sculptural Iridescent Down Puffer',
    description: 'Goose-down insulated statement coat constructed from light-reflecting metallic nylon fabric.',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
    tag: 'RUNWAY',
    category: 'Outerwear',
    dopamineScore: 1850,
    sizes: ['S', 'M', 'L'],
    stock: 12,
    rating: 4.7,
    reviewsCount: 14,
    isDrop: false,
    reviews: [],
  },

  // --- TAILORING & DRESSES ---
  {
    title: 'Velvet Jacquard Evening Blazer',
    description: 'Tailored slim-fit tuxedo jacket featuring structured shoulders, satin peak lapels, and ornate floral weave.',
    price: 3400,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
    tag: 'VIP EVENING',
    category: 'Tailoring',
    dopamineScore: 2200,
    sizes: ['48EU', '50EU', '52EU', '54EU'],
    stock: 6,
    rating: 4.9,
    reviewsCount: 11,
    isDrop: false,
    reviews: [
      {
        author: 'Antoine C.',
        rating: 5,
        comment: 'Wore this to a gala—got non-stop compliments all night.',
        date: '5 days ago',
        verifiedPurchase: true,
      },
    ],
  },
  {
    title: 'Architectural Silk Midi Dress',
    description: 'Asymmetrical neckline dress in heavy crepe de chine silk with hidden boning structure.',
    price: 3100,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1200&q=85',
    tag: 'HAUTE COUTURE',
    category: 'Dresses',
    dopamineScore: 2600,
    sizes: ['FR 36', 'FR 38', 'FR 40'],
    stock: 7,
    rating: 4.8,
    reviewsCount: 15,
    isDrop: false,
    reviews: [],
  },

  // --- TOPS & KNITWEAR ---
  {
    title: 'Heavyweight Silk Satin Shirt',
    description: 'Fluid Mulberry silk button-down detailed with contrast white piping and mother-of-pearl buttons.',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=1200&q=85',
    tag: 'LOUNGE LUXE',
    category: 'Tops',
    dopamineScore: 1400,
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 20,
    rating: 4.8,
    reviewsCount: 22,
    isDrop: false,
    reviews: [],
  },
  {
    title: 'Distressed Mohair Blend Crewneck',
    description: 'Hand-knitted brush mohair sweater featuring laddering accents and dropped shoulders.',
    price: 1150,
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1200&q=85',
    tag: 'STREETWEAR',
    category: 'Knitwear',
    dopamineScore: 1650,
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 14,
    rating: 4.6,
    reviewsCount: 19,
    isDrop: false,
    reviews: [],
  },
  {
    title: 'Boxy Vintage Sun-Faded Heavy Tee',
    description: '400GSM combed organic cotton with enzyme wash treatment and subtle hand-distressed collar edges.',
    price: 480,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=85',
    tag: 'ESSENTIAL',
    category: 'Tops',
    dopamineScore: 850,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 35,
    rating: 4.7,
    reviewsCount: 45,
    isDrop: false,
    reviews: [],
  },

  // --- DENIM & TROUSERS ---
  {
    title: 'Japanese Selvage Cargo Denim',
    description: '16oz raw indigo denim trousers featuring 3D utility cargo pockets and cinch-adjustable leg cuffs.',
    price: 1650,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=85',
    tag: 'RAW DENIM',
    category: 'Bottoms',
    dopamineScore: 1600,
    sizes: ['30W', '32W', '34W', '36W'],
    stock: 15,
    rating: 4.8,
    reviewsCount: 19,
    isDrop: false,
    reviews: [],
  },
  {
    title: 'Pleated Wide-Leg Wool Trousers',
    description: 'Relaxed tailored pants crafted from tropical weight Italian wool with deep double front pleats.',
    price: 1100,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=85',
    tag: 'MINIMALIST',
    category: 'Bottoms',
    dopamineScore: 1250,
    sizes: ['28W', '30W', '32W', '34W'],
    stock: 18,
    rating: 4.9,
    reviewsCount: 16,
    isDrop: false,
    reviews: [],
  },

  // --- FOOTWEAR & SNEAKERS ---
  {
    title: 'Veloce Leather High-Top Sneakers',
    description: 'Handcrafted Italian calfskin high-tops with padded ankle collars and gold foiled crest branding.',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=85',
    tag: 'NEW SEASON',
    category: 'Footwear',
    dopamineScore: 1900,
    sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44'],
    stock: 10,
    rating: 4.9,
    reviewsCount: 31,
    isDrop: false,
    reviews: [],
  },
  {
    title: 'Monolith Chunky Lug Derby',
    description: 'Polished brushed leather lace-ups set on an exaggerated 55mm lug sole with silver heel clips.',
    price: 1850,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=85',
    tag: 'MUST HAVE',
    category: 'Footwear',
    dopamineScore: 2100,
    sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44'],
    stock: 7,
    rating: 5.0,
    reviewsCount: 24,
    isDrop: false,
    reviews: [],
  },
  {
    title: 'Chelsea Lug Boots in Espresso Suede',
    description: 'Water-resistant Italian suede boots with elastic side gussets and storm-welted rubber soles.',
    price: 1600,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=1200&q=85',
    tag: 'AUTUMN DROP',
    category: 'Footwear',
    dopamineScore: 1750,
    sizes: ['EU 41', 'EU 42', 'EU 43', 'EU 44'],
    stock: 9,
    rating: 4.8,
    reviewsCount: 15,
    isDrop: false,
    reviews: [],
  },
];

async function seed() {
  if (!process.env.MONGODB_URI) {
    console.error('❌ MONGODB_URI is missing in process.env');
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGODB_URI);
  console.log('📡 Connected to MongoDB database...');

  await Product.deleteMany({});
  console.log('🧹 Cleared old products...');

  const inserted = await Product.insertMany(sampleProducts);
  console.log(`✅ Successfully seeded ${inserted.length} high-clout items!`);

  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seeding failed:', err);
  process.exit(1);
});